version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: circleci/openjdk:stretch 
    steps:
      - checkout
      - run:
          name: pwd and content of dir
          command: pwd; ls -lah 
      - run:
          name: Build
          command: mvn -f scholl/pom.xml -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn -f scholl/pom.xml test

workflows:
  sample: 
    jobs:
      - build-and-test
